name: eas-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Print Node/NPM versions
        run: |
          node -v
          npm -v

      - name: Use Expo + EAS
        uses: expo/expo-github-action@v8
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          eas-version: latest

      - name: Install deps
        run: npm install --legacy-peer-deps

      - name: Lint & Test
        run: |
          npm run lint:check || true
          npm test || true

      - name: EAS iOS preview build (simulator)
        run: eas build --platform ios --profile preview --non-interactive
